# Swift 4.1, SwiftLint 0.25.0
reporter: xcode
opt_in_rules:
  - force_unwrapping
  - vertical_whitespace
  - empty_count
  - closure_end_indentation
  - closure_spacing
  - explicit_init
  - first_where
  - nimble_operator
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - prohibited_super_call
  - redundant_nil_coalescing
disabled_rules:
  - todo
  - identifier_name
excluded:
  - Carthage
  - Pods
  - vendor
  - Viper/Resources/R.generated.swift
cyclomatic_complexity:
  warning: 15
line_length: 200
file_length: 500
force_unwrapping: error
function_parameter_count:
  - 6
  - 8
function_body_length:
  - 80
  - 100
type_body_length:
  - 300
  - 500
type_name:
  min_length: 1
  max_length: 40
identifier_name:
  min_length: 1
  max_length: 40
custom_rules:
  disable:
    name: "Disable Rule In Code"
    regex: '(swiftlint:disable)'
    message: "Please do not disable rule in code. "
    severity: error
    match_kinds: comment
  outlet_collection:
    name: "outlet_collection"
    regex: '(@IBOutletCollection)'
    message: "IBOutletCollection is not permitted. "
    severity: error
